const fs = require('fs');
let code = fs.readFileSync('src/components/scenes/ReviewScene.tsx', 'utf8');
code = code.replace(/const promptText = \\`/, 'const promptText = `');
code = code.replace(/\\$\\{text\\}/, '${text}');
code = code.replace(/\\$\\{accepted\.map/, '${accepted.map');
code = code.replace(/\\$\\{i \+ 1\\}/, '${i + 1}');
code = code.replace(/\\$\\{s\.type\\}/, '${s.type}');
code = code.replace(/\\$\\{s\.severity\\}/, '${s.severity}');
code = code.replace(/\\$\\{s\.content\\}/, '${s.content}');
code = code.replace(/\\$\\{s\.quote \? \\` \(原文："\\$\\{s\.quote\\}"\)\\` : ''\\}/, '${s.quote ? ` (原文："${s.quote}")` : \'\'}');
code = code.replace(/用 Markdown 格式输出。\\`/, '用 Markdown 格式输出。`');
fs.writeFileSync('src/components/scenes/ReviewScene.tsx', code);
